language: node_js
node_js:
  - '4'
  - '6'

sudo: required
dist: trusty

addons:
  rethinkdb: "2.3"
  code_climate:
    repo_token: 6c06bb655d903f47c8c6a889709c089660f95128addec8624acda75a344d1db0

before_install:
  - npm install -g codeclimate-test-reporter

script:
  - make coverage

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
